# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# See https://github.com/jan-warchol/selenized for color values
format = """$username$hostname$directory$git_branch$git_status$time$kubernetes$line_break\
$character"""

command_timeout = 1000

[character]
error_symbol = "\\$"
success_symbol = "\\$"

[directory]
style = "green"
truncate_to_repo = false
truncation_length = 10
truncation_symbol = "…/"

[git_branch]
symbol = ""

[git_status]
deleted = "x"
style = "blue"

[hostname]
ssh_only = false
style = "yellow"

[kubernetes]
disabled = false
format = "using [$symbol$context/$namespace]($style)"
style = "green"
symbol = ""

[[kubernetes.contexts]]
context_pattern = "\\W*prod\\W*"
style = "bold red"
symbol = "🚨 "
context_alias = "prod"

[[kubernetes.contexts]]
context_pattern = "docker-context"
style = "bold blue"
symbol = "🐋 "
context_alias = "Docker"

[time]
disabled = false
style = "bold red"
time_format = "%F %T"

[username]
format = "[$user]($style) at "
show_always = true
style_root = "red"
style_user = "bold red"
