# yaml-language-server:$schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-config-schema.json
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Configures how markdown files are linted

MD013:
  line_length: 120
  tables: false

MD024:
  siblings_only: true

MD059: false
