#!/usr/bin/env bash
# shellcheck disable=SC2154

# Make vim the default editor.
export EDITOR='vim';

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history. Also delete duplicates from the history.
export HISTCONTROL='ignoreboth:erasedups';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Colorize manual pages. See https://unix.stackexchange.com/a/108840 for details
export LESS_TERMCAP_mb="${red}"; # start blink
export LESS_TERMCAP_md="${yellow}"; # start bold
export LESS_TERMCAP_me="${reset}"; # turn off bold, blink and underline
export LESS_TERMCAP_se="${reset}"; # stop standout
export LESS_TERMCAP_so="${blue}"; # start standout
export LESS_TERMCAP_ue="${reset}"; # stop underline
export LESS_TERMCAP_us="${green}"; #start underline

# Don’t clear the screen after quitting a manual page.
#export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
GPG_TTY=$(tty);
export GPG_TTY

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1;
